name: ekko
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  bitsdojo_window: ^0.1.4
  # bitsdojo_window: ^0.1.6
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.1.3
  flutter_highlight: ^0.7.0
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.6.0
  intl: ^0.19.0
  path: ^1.8.3
  path_provider: ^2.1.1
  provider: ^6.0.5
  # regex_pattern_text_field: ^1.0.7
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+3
  url_launcher: ^6.2.1
  window_manager: ^0.3.7
    # window_manager: ^0.3.7

  # Using my own foked regex_pattern_text_field
  regex_pattern_text_field:
    git:
      url: https://github.com/Empitrix/regex_pattern_text_field
      ref: master
  
  awesome_text_field:
    path: "F:/Flutter/awesome_text_field"
    # git:
    #   url: https://github.com/Empitrix/regex_pattern_text_field
    #   ref: master
        

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/ekko.png"
  min_sdk_android: 21
  background_color: "#000000"
  windows:
    generate: true
    icon_size: 256

flutter:
  uses-material-design: true

  assets:
    - assets\icon\icon.png
    - assets\icon\icon.svg
    - assets\icon\ekko.png

  fonts:
    - family: Rubik
      fonts:
        - asset: assets\fonts\Rubik-Regular.ttf
    - family: SauceCodeProNerdFont
      fonts:
        - asset: assets\fonts\SauceCodeProNerdFont-Regular.ttf
    - family: RobotoMono
      fonts:
        - asset: assets\fonts\RobotoMono-Regular.ttf
